### ISSUE TITLE
v1.0 not work 

### ISSUE THREAD

**Issue by Ghalebor** [DomiKamu/OhmerPrems#1]
Hi Dominiqe 
Windows version of OhmerPrems has only Kick 1 from Oberheim DMX. Turning knob not change anything. Cheers!!

**Comment by Petervos2018** [comment]
Hi Ghalebor this works different than you think.

> Momentary button to select active channel (if its LED is off). When pressing button on already active channel, the LED blinks, indicating channel edit. The related item to edit also blink in dot-matrix display (DMD). When drum machine name is blinking, press the channel button (again) to change its instrument. Turn the rotary encoder clockwise or counter-clockwise to select next / previous drum machine, or its instrument. No need to validate anything, your choice is immediately applied! Also, please notice while channel LED is blinking (meaning you're editing active channel), if you don't touch the rotary encoder nor any button, the edit mode ends - automatically - after 30 seconds (it's a kind of timeout). **Rotary encoder doesn't have effect while LED doesn't blink, to avoid unwanted changes.**

Or watch this : https://youtu.be/7e7qjuJyDj0?t=221

**Comment by DomiKamu** [comment]
Thanks Petervos2018.

@Ghalebor : click first on channel bouton, when LED is blinking you can change blinking drum machine. Then press the button again to edit the machine's instrument ...

So it's not an issue ;)
