### ISSUE TITLE
Ohmer Prems free Mac build

### ISSUE THREAD

**Issue by Torinbob** [DomiKamu/OhmerPrems#2]
Hi Dominique,

Here's the free Mac build

[OhmerPrems-2.0.0-mac.vcvplugin.zip](https://github.com/DomiKamu/OhmerPrems/files/7270171/OhmerPrems-2.0.0-mac.vcvplugin.zip)

**Comment by DomiKamu** [comment]
Mac build added to "pre-release",
Thank you Steve!
